package ca.bradj.questown.town.names;

import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.ForgeRegistries;

import ca.bradj.questown.mc.Compat;

/**
 * Derives a townie's display name from an item's registry path.
 *
 * <p>Names come from the world: *Diamond*, *Stone*, *Shovel* — which gives
 * Minecraft-native flavour for free and scales with modded content. The source is
 * the item's registry <em>path</em> ({@code Compat.getItemId(item).getPath()}),
 * not its display name. The path is already tokenized on '_', is locale-independent
 * (a stored name should not shift when the player changes language), and carries
 * no formatting codes a translatable display name can.
 *
 * <p>The algorithm: tokenize the path, drop tokens on a stoplist (material
 * states, forms, qualifiers), reject tokens containing digits, keep tokens of
 * length {@code MIN_LEN..MAX_LEN}, take the first survivor and title-case it.
 * A curated blocklist then rejects results that survive everything and still
 * read badly (Rotten, Poisonous).
 *
 * <p>Only the {@code minecraft:} pool ships, generated by {@link #generatePool()}
 * and checked in as a reviewable golden file (see {@code TownieNamesTest}). A
 * stoplist change produces a reviewable diff, caught by the test rather than by a
 * player meeting a townie called *Tarnished*.
 *
 * <p>The name is persisted as a resolved string on the townie, not an item id, so
 * it keeps meaning if the mod that produced it is removed.
 */
public final class TownieNames {

    private TownieNames() {}

    /** Namespace the checked-in pool is scoped to. Config to widen (future). */
    public static final String DEFAULT_NAMESPACE = "minecraft";

    /** Material states / finishes: describe a condition, not a thing. */
    static final Set<String> MATERIALS = set(
            "waxed", "exposed", "weathered", "oxidized", "cut",
            "polished", "chiseled", "smooth", "cracked", "mossy",
            "raw", "cooked", "damaged"
    );

    /** Forms / generics: the shape a name shares with many items. */
    static final Set<String> FORMS = set(
            "block", "item", "slab", "stairs", "wall", "fence", "gate",
            "door", "trapdoor", "button", "plate", "pane", "bars",
            "brick", "bricks", "tile", "tiles", "ingot", "nugget",
            "dust", "shard", "powder", "ore", "log", "planks",
            "sapling", "seeds", "bottle", "bucket"
    );

    /** Qualifiers: size / position modifiers. */
    static final Set<String> QUALIFIERS = set(
            "lesser", "greater", "small", "large", "tiny", "huge",
            "upper", "lower", "dead", "infested"
    );

    /** Results that survive the algorithm and still read badly. Not algorithmic. */
    static final Set<String> BLOCKLIST = set(
            "rotten", "poisonous", "suspicious"
    );

    static final int MIN_LEN = 3;
    static final int MAX_LEN = 10;

    private static Set<String> set(String... tokens) {
        Set<String> out = new LinkedHashSet<>();
        for (String t : tokens) {
            out.add(t);
        }
        return out;
    }

    /**
     * Pure: derive a name from a registry path, or {@code null} when no token
     * survives the filters (or the result is blocklisted). Locale-independent.
     */
    public static String nameFromPath(String path) {
        if (path == null) {
            return null;
        }
        String[] tokens = path.split("_");
        for (String token : tokens) {
            if (isStoplisted(token)) {
                continue;
            }
            if (hasDigit(token)) {
                continue;
            }
            if (!inLengthRange(token.length())) {
                continue;
            }
            String name = titleCase(token);
            if (BLOCKLIST.contains(token)) {
                return null;
            }
            return name;
        }
        return null;
    }

    /**
     * Runtime: the name for an item, or {@code null} when its namespace is not
     * permitted or no token survives. The namespace gate is the default
     * {@code minecraft:}-only bound; a future config widens it.
     */
    public static String nameForItem(ResourceLocation id) {
        if (id == null || !DEFAULT_NAMESPACE.equals(id.getNamespace())) {
            return null;
        }
        return nameFromPath(id.getPath());
    }

    /**
     * Runtime: the full pool of names over the registered items, keyed by
     * registry path. This is the one code path that will later be pointed at
     * other namespace sets for mod-sourced names.
     */
    public static Map<String, String> generatePool() {
        Map<String, String> pool = new LinkedHashMap<>();
        for (Item item : ForgeRegistries.ITEMS.getValues()) {
            ResourceLocation id = Compat.getItemId(item);
            if (id == null || !DEFAULT_NAMESPACE.equals(id.getNamespace())) {
                continue;
            }
            String name = nameFromPath(id.getPath());
            if (name != null) {
                pool.put(id.getPath(), name);
            }
        }
        return pool;
    }

    static boolean isStoplisted(String token) {
        return MATERIALS.contains(token) || FORMS.contains(token) || QUALIFIERS.contains(token);
    }

    static boolean hasDigit(String token) {
        for (int i = 0; i < token.length(); i++) {
            if (Character.isDigit(token.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    static boolean inLengthRange(int len) {
        return len >= MIN_LEN && len <= MAX_LEN;
    }

    static String titleCase(String token) {
        String lower = token.toLowerCase(Locale.ROOT);
        if (lower.isEmpty()) {
            return "";
        }
        return Character.toUpperCase(lower.charAt(0)) + lower.substring(1);
    }
}
